'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Mail, MessageCircle, Send } from 'lucide-react'
import { Nav } from '@/components/nav'

export default function ContactPage() {
  const [sent, setSent] = useState(false)
  return <div className="min-h-screen bg-cream"><Nav /><main className="mx-auto w-full max-w-5xl px-4 py-10 sm:px-6 sm:py-16"><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-sage"><ArrowLeft className="size-4" /> Back to home</Link><div className="mt-8 grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-rose">Contact us</p><h1 className="mt-3 font-display text-4xl leading-tight sm:text-6xl">We are here to help</h1><p className="mt-5 leading-7 text-muted-foreground">Have a question about a place, an application, or listing your space? Send us a note and the humdum team will get back to you.</p><div className="mt-8 grid gap-3"><div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4"><Mail className="size-5 text-rose" /><div><p className="text-xs text-muted-foreground">Email</p><p className="font-semibold text-sage">hello@humdum.pk</p></div></div><div className="flex items-center gap-3 rounded-2xl border border-border bg-card p-4"><MessageCircle className="size-5 text-rose" /><div><p className="text-xs text-muted-foreground">Response time</p><p className="font-semibold text-sage">Usually within one business day</p></div></div></div></div><form onSubmit={(event) => { event.preventDefault(); setSent(true) }} className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-7">{sent ? <div className="py-10 text-center"><Send className="mx-auto size-9 text-sage" /><h2 className="mt-4 font-display text-3xl">Message sent</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Thanks for reaching out. We will be in touch soon.</p><button type="button" onClick={() => setSent(false)} className="mt-6 rounded-full border border-sage px-5 py-2.5 text-sm font-semibold text-sage">Send another message</button></div> : <div className="grid gap-4"><label className="grid gap-2 text-sm font-semibold">Your name<input required className="min-h-12 rounded-xl border border-border bg-cream px-4 font-normal outline-none focus:border-sage" /></label><label className="grid gap-2 text-sm font-semibold">Email address<input required type="email" className="min-h-12 rounded-xl border border-border bg-cream px-4 font-normal outline-none focus:border-sage" /></label><label className="grid gap-2 text-sm font-semibold">How can we help?<textarea required rows={5} className="resize-y rounded-xl border border-border bg-cream px-4 py-3 font-normal outline-none focus:border-sage" /></label><button type="submit" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-rose px-5 py-3 text-sm font-semibold text-white hover:bg-rose-dark"><Send className="size-4" /> Send message</button></div>}</form></div></main></div>
}
